name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      # Checkout
      - uses: actions/checkout@v4

      - name: Build Eigen
        run: ./scripts/build-eigen-jetson-r32.sh
