name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      # Checkout
      - uses: actions/checkout@v4

      - name: Build Eigen (x64)
        run: ./scripts/build.sh x64 eigen

      - name: Build Eigen (Jetson R32)
        run: ./scripts/build.sh jetson-r32 eigen
